version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=84d5bSeBdYQRrq77
      - MYSQL_DATABASE=qb
      - MYSQL_USER=qb
      - MYSQL_PASSWORD=kf6JdUXBHCU5Br47
    ports:
      - "3666:3306"
    volumes:
      -  ./docker/mysql/init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=qb
      - POSTGRES_USER=qb
      - POSTGRES_PASSWORD=Y2yUc9jN4GNXfC6Y
    ports:
      - "5662:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  cli:
    image: abtercms/php:80-dev
    links:
      - mysql
      - postgres
    environment:
      - MYSQL_DATABASE=qb
      - MYSQL_USER=qb
      - MYSQL_PASSWORD=kf6JdUXBHCU5Br47
      - POSTGRES_DB=qb
      - POSTGRES_USER=qb
      - POSTGRES_PASSWORD=Y2yUc9jN4GNXfC6Y
    volumes:
      - .:/qb
      - ./docker/php/conf.d/ast-on.ini:/usr/local/etc/php/conf.d/ast-on.ini:ro
      - ./docker/php/conf.d/xdebug-on.ini:/usr/local/etc/php/conf.d/xdebug-on.ini:ro
      - ./docker/php/conf.d/zzz_020_general.ini:/usr/local/etc/php/conf.d/zzz_020_general.ini:ro
      - ./docker/php/conf.d/zzz_500_local.ini:/usr/local/etc/php/conf.d/zzz_500_local.ini:ro
    working_dir: /qb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    links:
      - mysql
      - postgres
    ports:
      - "8080:8080"